### ISSUE TITLE
WxPayConfig文件夹中将类改成了单例、常量改成了静态变量导致原有的调用方式错误

### ISSUE THREAD

**Issue by lscho** [goldeagle/wx-pay-api#2]
```
public static $APPID = '你的微信公众号 APPID';
```
这种方式定义的静态变量只能用  WxPayConfig::$APPID 来获取吧？

原来的 WxPayConfig::APPID 获取的是常量

#已经fix

**Comment by CoderZYLiao** [comment]
WxPayConfig::APPID 同样问题

**Comment by CoderZYLiao** [comment]
弱弱地问一句大神，    /**
     * 设置订单总金额，只能为整数，详见支付金额
     * @param string $value
     **/
    public function setTotalFee($value)
    {
        $this->values['total_fee'] = $value;
    }

    /**
     * 获取订单总金额，只能为整数，详见支付金额的值
     * @return string 值
     **/
    public function getTotalFee()
    {
        return $this->values['total_fee'];
    }
为什么只能设置整数啊？

**Comment by CoderZYLiao** [comment]
好吧，看了官方文档，原来单位是分。。。。。。。。交易金额默认为人民币交易，接口中参数支付金额单位为【分】，参数值不能带小数。对账单中的交易金额单位为【元】。
外币交易的支付金额精确到币种的最小单位，参数值不能带小数点。

**Comment by goldeagle** [comment]
issue fixed
